### ISSUE TITLE
Cohort construction is embedded in computeAggregateCovariateAnalyses

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Characterization#15]
I was testing a use case with a large set of target/outcome combinations using multiple aggregateFeatureExtraction setting

> aggregateCovariateSettings1 <- createAggregateCovariateSettings(..)
> aggregateCovariateSettings2 <- createAggregateCovariateSettings(...)
> characterizationSettings <- createCharacterizationSettings(
>     aggregateCovariateSettings = list(
>       aggregateCovariateSettings1,
>       aggregateCovariateSettings2
>       )
>   )

And probably because createCohortsOfInterest is called from inside computeAggregateCovariateAnalyses without incremental mode

https://github.com/OHDSI/Characterization/blob/bb5ca286d8808cfd8fd45ed17fcfaaa6becd20c3/R/AggregateCovariates.R#L235

the createCohortsOfInterest appeared to execute for each item in the list aggregateCovariateSettings .  This took some time and was also silent, probably because of this

https://github.com/OHDSI/Characterization/blob/bb5ca286d8808cfd8fd45ed17fcfaaa6becd20c3/R/AggregateCovariates.R#L274

Would it be possible to consider some form of incremental mode to reduce re-execution of cohort construction for every aggregateCovariateSetting item? Also, would it be possible to show cohort construction in the log (e.g. a log 'Construction cohort' followed by progressBar = FALSE)

**Comment by jreps** [comment]
How come you had different settings for the same cohorts?  What needed to be changed?  If it is something like you needed multiple TAR then maybe we can just add that ability, so you would only need one setting.

**Comment by jreps** [comment]
actually - the cohort creation will be different for each TAR, so that has to be separate.  The only cohorts that don't depend on TAR are T and O but these are just simple select * into statements so not really a bottleneck.

**Comment by gowthamrao** [comment]
I think you are correct? 

The reason why I thought this was an issue was that I thought we could not combine covariateSettings in FeatureExtraction. So i thought of combining aggregateCovariateSetting of Characterization instead using the same temporal windows but different covariateSettings.

But you can combine covaraiteSetting in FeatureExtraction.

But now Characterization package does not support such a combined covariateSettings as reported in this issue

https://github.com/OHDSI/Characterization/issues/18
