### ISSUE TITLE
Temp tables not being dropped on DataBricks

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Characterization#61]
Hi - I ran Characterization v2.0.1 using Strategus on DataBricks and I believe there are some temp tables that are not being dropped per this screenshot:

![image](https://github.com/user-attachments/assets/085f2dcf-8416-4721-80ed-a8d108367375)

Let me know if you need further details.

**Comment by jreps** [comment]
Odd there is code https://github.com/OHDSI/Characterization/blob/main/inst/sql/sql_server/DropTimeToEvent.sql to drop the tables and I see this being called into tte.  The nc_set is coming from a non-char package though.

**Comment by anthonysena** [comment]
Yes, the nc_set is coming from CohortGenerator per https://github.com/OHDSI/CohortGenerator/issues/188. I'll take a look in that package to see what's happening.

**Comment by anthonysena** [comment]
I'm still unclear why this is happening but will close this out since it does not appear to be anything specific to this package.

**Comment by anthonysena** [comment]
In speaking with @schuemie, we should update our SQL so that we're dropping temp tables ahead of creating them in an effort to prevent problems for those RDBMS platforms that use a tempEmulationSchema. Putting this here for reference to illustrate that point:

https://github.com/OHDSI/CohortMethod/blob/main/inst/sql/CreateCohorts.sql#L33

**Comment by anthonysena** [comment]
Closing this out since my review of the code base shows attempts to drop temp tables before creating them. I think this particular issue was a result of a failed run.
